# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6fcd53b5d23cdbce003c053f8aea78e6353d6d39709fcb47d6cf9caf0cc38a71a1041c1f1d91780c439f6cbf4454a1c420df53975508fce9d8f8df26e26b5b49

test:
  secret_key_base: dd65724cf634639933c4cd4211e5f4405956f474ceb42b90cee5738e23c9677ac2336322d089fd7527afbd56915a8f266366cf4b2c1cf71c54ea05c6ec5ea268

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
